# # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#
# default.yml
#
# Use this global manifest (`default.yml`) to configure
# top-level settings for your organization as a whole, and
# controls/reports/etc that apply to all of your fleets.
#
# To see all supported options, check out:
#   • https://fleetdm.com/docs/configuration/yaml-files
#
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

org_settings:
  org_info:
    ###########################################################
    # The name of your organization is displayed to end users
    # during the setup experience for new hardware, and to admins
    # in the Fleet UI.
    #
    # Read more:
    #   • https://fleetdm.com/docs/configuration/yaml-files#org-info
    ###########################################################
    org_name: My organization

  server_settings:
    ###########################################################
    # The server URL where Fleet is running.
    #
    # Note: This is configured as a repository "secret" just so
    # that it can be more easily used in the CI/CD workflow
    # configurations.
    ###########################################################
    server_url: $FLEET_URL

  ###########################################################
  # Uncomment to use single sign-on (SSO) for admins accessing Fleet.
  #
  # Read more:
  #   • https://fleetdm.com/docs/configuration/yaml-files#sso-settings
  #   • https://fleetdm.com/docs/deploy/single-sign-on-sso
  ###########################################################
  # sso_settings:
  #   idp_name: "Okta" # e.g. "Entra", "Okta", "Google Workspace", etc.  (This appears to admins on the login screen as a "Sign in with ________" button.)
  #   metadata_url: "https://okta.com/replace-this-url" # This must exactly match the "IdP metadata URL" provided by your identity provider (IdP) when setting up this integration.
  #   entity_id: "fleet-admins" # This must exactly match the "Entity ID" field you chose when setting up this integration in your identity provider (IdP).

  mdm:
    ###########################################################
    # Uncomment to use single sign-on (SSO) to authenticate
    # new computers enrolling in Fleet during end user setup.
    #
    # Read more:
    #   • https://fleetdm.com/docs/configuration/yaml-files#end-user-authentication
    #   • https://fleetdm.com/guides/setup-experience#end-user-authentication
    ###########################################################
    # end_user_authentication:
    #   idp_name: "Okta"  # e.g. "Entra", "Okta", "Google Workspace", etc. (Displayed to end users.)
    #   metadata_url: "https://okta.com/replace-this-url" # This must exactly match the "IdP metadata URL" provided by your identity provider (IdP) when setting up this integration.
    #   entity_id: "fleet-end-users" # This must exactly match the "Entity ID" field you chose when setting up this integration in your identity provider (IdP).

    ###########################################################
    # Uncomment when you are ready to start using zero-touch enrollment
    # for Apple devices via Apple Business (AB).
    #
    # Read more:
    #   • https://fleetdm.com/docs/configuration/yaml-files#apple-business-manager
    #   • https://fleetdm.com/guides/apple-mdm-setup#apple-business-manager-abm
    ###########################################################
    # apple_business:
    #   - organization_name: "My Company, Inc." # This must exactly match the organization name in Apple Business (AB).
    #     macos_fleet: "💻 Workstations" # Where new macOS devices from AB will appear

    ###########################################################
    # Uncomment to start using Apple's volume purchase program (VPP)
    # for making software available from the App Store and managing
    # software licenses.
    #
    # Read more:
    #   • https://fleetdm.com/docs/configuration/yaml-files#volume-purchasing-program
    #   • https://fleetdm.com/guides/apple-mdm-setup#volume-purchasing-program-vpp
    ###########################################################
    # volume_purchasing_program:
    #   - location: "My organization unit." # This must exactly match an "Organization Unit" name in Apple Business (AB). Apple previously called this "location." Fleet will rename it to "organization unit" in the next major version.
    #     fleets:
    #       - "💻 Workstations"
    #       - "📱🔐 Personal mobile devices"

controls:
  ###########################################################
  # Uncomment when you are ready to migrate Macs to Fleet
  # from a different MDM server, especially devices running
  # macOS ≤v26.
  #
  # For more information about what this does, see:
  #   • https://fleetdm.com/docs/configuration/yaml-files#macos-migration
  #   • https://fleetdm.com/guides/mdm-migration#end-user-workflow
  #
  # Note: This is a global setting that cannot be applied per-fleet.
  ###########################################################
  # macos_migration:
  #   enable: true
  #   mode: voluntary # Start with "voluntary", then change this to "forced" closer to the deadline.
  #   webhook_url: "https://your-custom-webhook-or-one-provided-off-the-shelf-by-fleet-for-the-mdm-you-are-coming-from.example.com/webhooks/receive-from-fleet"
  #   # ^ When end users click "Migrate to Fleet", this webhook is triggered.
  #   # By convention it looks up the device and unmanages it in the old MDM,
  #   # then enrolls the device in Fleet.  Unsure?  Get help @ fleetdm.com/support.

  ###########################################################
  # Uncomment when you are ready to start using Fleet's Windows MDM features.
  # 
  # Read more:
  #   • https://fleetdm.com/guides/windows-mdm-setup
  ###########################################################
  # windows_enabled_and_configured: true


###########################################################
# Labels are static or dynamic groupings of computers for
# scoping, reporting, and more.  Use labels for everything
# from "x86 macs" to "finance department" to "needs new battery".
#
# For more, see:
#   • https://fleetdm.com/docs/configuration/yaml-files#labels
#   • https://fleetdm.com/guides/managing-labels-in-fleet
#
# (Optional) You can choose to manage labels in the Fleet GUI
# instead of in your git repo by **commenting out** `labels`
# below and removing the `labels/` folder.
#
# > Note: If you exclude `labels` from your git repo, then any
# > AI-assisted tools you may be using like Claude/Copilot/Kilocode
# > won't be able to see them as easily for use in scoping,
# > and could make it harder to do prompts like, for example:
# > "Make sure everyone in finance has the latest version of Excel"
###########################################################
labels:
  - paths: ./labels/*.yml

software:
  packages:
    # macOS apps
    - path: ../lib/macos/software/fleet-keynote-theme.yml # Fleet Keynote theme for macOS
      self_service: true
      labels_include_any:
        - "Keynote 14 installed"
      categories:
        - Productivity
    - path: ../lib/macos/software/nudge-assets.yml # Nudge assets for macOS
      self_service: false
      categories:
        - Utilities
    - path: ../lib/macos/software/fleet-desktop-launch-agent.yml
      self_service: false
      labels_include_any:
        - "Macs with Fleet Desktop.app launch agent MDM profile"
      categories:
        - Utilities
    - path: ../lib/macos/scripts/enable-touch-id-sudo.sh # Enable Touch ID for sudo
      display_name: "Enable Touch ID for sudo"
      self_service: true
      categories:
        - Security
      icon:
        path: ../lib/all/icons/touch-id.png
    # Linux apps
    - path: ../lib/linux/software/1password-deb.yml # 1Password for Ubuntu
      self_service: true
      setup_experience: true
      categories:
        - Security
      labels_include_any:
        - "Debian-based Linux hosts"
    - path: ../lib/linux/software/1password-rpm.yml # 1Password for RedHat
      self_service: true
      setup_experience: true
      categories:
        - Security
      labels_include_any:
        - "RPM-based Linux hosts"
    - path: ../lib/linux/software/zoom-deb.yml # Zoom for Ubuntu
      self_service: true
      setup_experience: true
      categories:
        - Communication
      labels_include_any:
        - "Debian-based Linux hosts"
    - path: ../lib/linux/software/zoom-rpm.yml # Zoom for RedHat
      self_service: true
      setup_experience: true
      categories:
        - Communication
      labels_include_any:
        - "RPM-based Linux hosts"
    - path: ../lib/linux/software/slack-deb.yml # Slack for Ubuntu
      self_service: true
      setup_experience: true
      categories:
        - Communication
      labels_include_any:
        - "Debian-based Linux hosts"
    - path: ../lib/linux/software/slack-rpm.yml # Slack for RedHat
      self_service: true
      setup_experience: true
      categories:
        - Communication
      labels_include_any:
        - "RPM-based Linux hosts"
    # Windows apps
    # Commenting out until #25407 is implemented
    # - path: ../lib/windows/software/zoom-arm.yml # Zoom for Windows (ARM)
    #  self_service: true
    #  categories:
    #    - Communication
    #  labels_include_any:
    #    - "ARM-based Windows hosts"
    # Commenting out until #25407 is implemented
    # - path: ../lib/windows/software/google-chrome-arm.yml # Google Chrome for Windows (ARM)
    #   self_service: true
    #   setup_experience: true
    #   categories:
    #     - Browsers
    #   labels_include_any:
    #     - "ARM-based Windows hosts"
    - path: ../lib/windows/software/okta-verify.yml # Okta Verify for Windows (x86)
      self_service: true
      setup_experience: true
      categories:
        - Security
      labels_include_any:
        - "x86-based Windows hosts"
  app_store_apps:
    - app_store_id: "361285480" # Keynote
      display_name: "Keynote"
      platform: darwin
      self_service: true
      categories:
        - Productivity
  fleet_maintained_apps:
    # macOS apps
    - slug: 1password/darwin # 1Password for macOS
      self_service: true
      setup_experience: true
      categories:
        - Security
    - slug: aws-vpn-client/darwin # AWS VPN Client for macOS
      self_service: true
      labels_include_any:
        - "IdP group: SAML-aws-vpn"
      categories:
        - Utilities
    - slug: google-chrome/darwin # Google Chrome for macOS
      self_service: true
      setup_experience: true
      categories:
        - Browsers
    - slug: firefox/darwin # Mozilla Firefox for macOS
      self_service: true
      labels_include_any:
        - Macs with Firefox installed
      categories:
        - Browsers
    - slug: brave-browser/darwin # Brave for macOS (ARM)
      self_service: true
      labels_include_any:
        - Macs with Brave Browser installed
      categories:
        - Browsers
    - slug: docker-desktop/darwin # Docker for macOS (ARM)
      self_service: true
      labels_include_any:
        - Macs with Docker Desktop installed
      categories:
        - Developer tools
    - slug: visual-studio-code/darwin # Microsoft Visual Studio for macOS (ARM)
      self_service: true
      labels_include_any:
        - Macs with Visual Studio Code installed
      categories:
        - Developer tools
    - slug: slack/darwin # Slack for macOS
      self_service: true
      setup_experience: true
      categories:
        - Communication
    - slug: zoom/darwin # Zoom for macOS
      self_service: true
      setup_experience: true
      categories:
        - Communication
        - Productivity
    - slug: okta-verify/darwin # Okta Verify for macOS
      self_service: true
      setup_experience: true
      categories:
        - Security
    - slug: santa/darwin # Santa for macOS
      self_service: true
      setup_experience: true
      categories:
        - Security
    - slug: fleet-desktop/darwin # Fleet Desktop for macOS
      self_service: true
      icon:
        path: ../lib/all/icons/fleet-desktop-icon.png
      categories:
        - Utilities
    - slug: claude/darwin # Claude for macOS
      self_service: true
      setup_experience: true
      categories:
        - Productivity
    - slug: github/darwin # GitHub Desktop for macOS
      self_service: true
      labels_include_any:
        - Macs with GitHub Desktop installed
      categories:
        - Developer tools
    - slug: utm/darwin # UTM for macOS
      self_service: true
      labels_include_any:
        - Macs with UTM installed
      categories:
        - Productivity
    - slug: postman/darwin # Postman for macOS
      self_service: true
      labels_include_any:
        - Macs with Postman installed
      categories:
        - Developer tools
    - slug: grammarly-desktop/darwin # Grammarly Desktop for macOS
      self_service: true
      labels_include_any:
        - Macs with Grammarly Desktop installed
      categories:
        - Productivity
    - slug: iterm2/darwin # iTerm2 for macOS
      self_service: true
      labels_include_any:
        - Macs with iTerm2 installed
      categories:
        - Developer tools
    - slug: sublime-text/darwin # Sublime Text for macOS
      self_service: true
      labels_include_any:
        - Macs with Sublime Text installed
      categories:
        - Developer tools
    - slug: parallels/darwin # Parallels Desktop for macOS
      self_service: true
      labels_include_any:
        - Macs with Parallels Desktop installed
      categories:
        - Productivity
    - slug: loom/darwin # Loom for macOS
      self_service: true
      labels_include_any:
        - Macs with Loom installed
      categories:
        - Productivity
    - slug: nudge/darwin # Nudge for macOS
      self_service: false
      setup_experience: true
      categories:
        - Utilities
    - slug: spotify/darwin # Spotify for macOS
      self_service: true
      labels_include_any:
        - Macs with Spotify installed
      categories:
        - Productivity
    - slug: rectangle/darwin # Rectangle for macOS
      self_service: true
      labels_include_any:
        - Macs with Rectangle installed
      categories:
        - Productivity
    - slug: logi-options+/darwin # Logi Options+ for macOS
      self_service: true
      labels_include_any:
        - Macs with Logi Options+ installed
      categories:
        - Productivity
    - slug: figma/darwin # Figma for macOS
      self_service: true
      labels_include_any:
        - Macs with Figma installed
      categories:
        - Productivity
    - slug: whatsapp/darwin # WhatsApp for macOS
      self_service: true
      labels_include_any:
        - Macs with WhatsApp installed
      categories:
        - Communication
    - slug: android-studio/darwin # Android Studio for macOS
      self_service: true
      labels_include_any:
        - Macs with Android Studio installed
      categories:
        - Developer tools
    - slug: zed/darwin # Zed for macOS
      self_service: true
      labels_include_any:
        - Macs with Zed installed
      categories:
        - Developer tools
    - slug: obsidian/darwin # Obsidian for macOS
      self_service: true
      labels_include_any:
        - Macs with Obsidian installed
      categories:
        - Productivity
    - slug: google-drive/darwin # Google Drive for macOS
      self_service: true
      labels_include_any:
        - Macs with Google Drive installed
      categories:
        - Productivity
    - slug: cursor/darwin # Cursor for macOS
      self_service: true
      labels_include_any:
        - Macs with Cursor installed
      categories:
        - Developer tools
    - slug: adobe-acrobat-reader/darwin # Adobe Acrobat Reader for macOS
      self_service: true
      labels_include_any:
        - Macs with Adobe Acrobat Reader installed
      categories:
        - Productivity
    - slug: adobe-acrobat-pro/darwin # Adobe Acrobat Pro for macOS
      self_service: true
      labels_include_any:
        - Macs with Adobe Acrobat Pro installed
      categories:
        - Productivity
    # Windows apps
    - slug: 1password/windows # 1Password for Windows
      self_service: true
      setup_experience: true
      categories:
        - Security
    - slug: slack/windows # Slack for Windows
      self_service: true
      setup_experience: true
      categories:
        - Communication
      labels_include_any:
        - "x86-based Windows hosts"
    - slug: claude/windows # Claude for Windows
      self_service: true
      setup_experience: true
      labels_include_any:
        - "x86-based Windows hosts"
      categories:
        - Productivity
    - slug: firefox/windows # Mozilla Firefox for Windows
      self_service: true
      categories:
        - Browsers
      labels_include_any:
        - "x86 Windows hosts with Firefox installed"
    - slug: google-chrome/windows # Google Chrome for Windows
      self_service: true
      setup_experience: true
      categories:
        - Browsers
      labels_include_any:
        - "x86-based Windows hosts"
    - slug: zoom/windows # Zoom for Windows (x86)
      self_service: true
      setup_experience: true
      categories:
        - Communication
      labels_include_any:
        - "x86-based Windows hosts"
    - slug: visual-studio-code/windows # Microsoft Visual Studio for Windows
      self_service: true
      labels_include_any:
        - "x86 Windows hosts with Visual Studio Code installed"
      categories:
        - Developer tools
    - slug: adobe-acrobat-reader/windows # Adobe Acrobat Reader for Windows
      self_service: true
      labels_include_any:
        - x86 Windows hosts with Adobe Acrobat Reader installed
      categories:
        - Productivity